# 課題4 テキストデータ分析
配点
- Q1, 1P
- Q2, 2P
- Q3, 4P
- Q4, 3P

In [1]:
# 必要なモジュールのimport
import numpy as np
import pandas as pd

## Q1
$n$-次元ベクトル空間における、任意の2つのベクトル、$ \vec{x}=(x_1,x_2,...,x_n)$、$\vec{y}=(y_1,y_2,...,y_n)$、の間のcos類似度 $cos( \vec{x}, \vec{y})$ は以下のように定義されます。

$cos( \vec{x}, \vec{y}) =  \frac{\vec{x}\cdot \vec{y}}{\|x\|_2\|y\|_2}=\frac{\Sigma^{n}_{i=1}{x_{i}y_{i}}}{\sqrt{\Sigma^{n}_{i=1}x_{i}^{2}}\sqrt{\Sigma^{n}_{i=1}y_{i}^{2}}}$

入力ベクトル $\vec{x}$, $\vec{y}$ をそれぞれ`NumPy` の配列として引数で受け取り、それらのベクトル間のcos類似度を計算して返す関数 `cos_sim` を完成させてください。

In [4]:
def cos_sim(vec1, vec2):
  p=0
  q=0
  r=0
  for i in range(len(vec1)):
    r+=vec1[i]*vec2[i]
    p+=vec1[i]**2
    q+=vec2[i]**2

  return r/((q**0.5)*(p**0.5))

`cos_sim()`関数が完成したら、以下のセルを実行して動作を確認してください。

In [5]:
print(round(cos_sim(np.array([1,0,1]), np.array([1,1,1])), 2))
print(round(cos_sim(np.array([1,1,1]), np.array([1,1,1])), 2))
print(round(cos_sim(np.array([-1,-1,-1]), np.array([1,1,1])), 2))

0.82
1.0
-1.0


結果は、`0.82`、`1.0`、`-1.0`、となります。結果が異なる場合は、作成した関数に誤りがないか確認してください。

## Q2
"course_list.csv"ファイルには以下のように各行に授業名のテキストデータ（文字コードはUTF8）が含まれています。以下では、このファイルを読み込み、各授業のベクトルを作成し、授業間の類似度を求めるコードを実装します。
```Python
## course_list.csvファイル
...
数理科学基礎
物性化学
政治Ⅰ
身体運動・健康科学実習Ⅰ（ﾒﾃﾞｨｶﾙｹｱ1）
スペイン語テクスト分析Ⅰ
英語二列Ｗ（ALESS）
応用倫理学
...
```

In [6]:
# Colaboratoryでは以下を実行して必要なファイルをダウンロード
!wget https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/course_list.csv

--2022-11-04 13:05:11--  https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/course_list.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27388 (27K) [text/plain]
Saving to: ‘course_list.csv’

course_list.csv     100%[===================>]  26.75K  --.-KB/s    in 0.001s  

2022-11-04 13:05:11 (18.8 MB/s) - ‘course_list.csv’ saved [27388/27388]



### Q2.1
引数`file`に与えられたファイル名のファイルを1行ずつ**順番に**読み込み、その各行を要素とするリストを作成して返す`create_list`関数を完成さてください。作成されたリストは変数`courses`で受け取ります。**以降の処理では、リスト`courses`のインデックスをその要素（授業名）のIDとして扱います**。

In [7]:
def create_list(file):
  return pd.read_csv(file, header=None, encoding="utf-8").values.flatten().tolist()

`create_list`関数が完成したら、以下のセルを実行して動作を確認してください。リストの長さ（授業の数）は`552`、講義"計算機プログラミング"のID（リスト`courses`のインデックス）は`198`となります。

In [8]:
courses = create_list('course_list.csv')
print(len(courses))
print(courses.index('計算機プログラミング'))

552
198


"keyword_list.csv"ファイルには以下のように各行に1単語が含まれています（文字コードはUTF8）。
```Python
## keyword_list.csvファイル
...
外国語
日本語
力学
身体運動
微分積分学
ロシア語
熱力学
線型代数学
イタリア語
物性
...
```
上記と同様に`create_list`関数により、"keywor_list.csv"ファイルを1行ずつ**順番に**読み込み、その各行を要素とするリストを作成します。作成されたリストは変数`vocab`で受け取ります。以降の処理では、リスト`vocab`のインデックスをその要素（単語）のIDとして扱います。リスト`vocab`は以降の処理における語彙となります。

In [9]:
# Colaboratoryでは以下を実行して必要なファイルをダウンロード
!wget https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/keyword_list.csv

--2022-11-04 13:05:18--  https://raw.githubusercontent.com/UTDataMining/2022A/master/ex4/keyword_list.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2513 (2.5K) [text/plain]
Saving to: ‘keyword_list.csv’

keyword_list.csv    100%[===================>]   2.45K  --.-KB/s    in 0s      

2022-11-04 13:05:18 (39.6 MB/s) - ‘keyword_list.csv’ saved [2513/2513]



以下のセルを実行して動作を確認してください。リストの長さ（単語の数）は`243`、単語"プログラミング"のID（リスト`vocab`のインデックス）は`145`、単語"英語"のID（リスト`vocab`のインデックス）は`0`となります。

In [10]:
vocab = create_list('keyword_list.csv')
print(len(vocab))
print(vocab.index('プログラミング'))
print(vocab.index('英語'))

243
145
0


### Q2.2
リスト`courses`と`vocab`を引数で受け取り、単語のID（リスト`vocab`のその単語のインデックス）をキー、授業名を1文書（document）と考えた時のその単語のDF（Document Frequency)を値とする辞書を作成して返す`count_df`関数を作成してください。作成された辞書は変数`df`で受け取ります。この場合、ある単語のDFはその単語を授業名に含む授業数に対応します。**単語が授業名に複数回含まれる場合でも1回と数えます**

In [11]:
def count_df(courses, vocab):
  dic={}
  for i in range(len(vocab)):
    for c in courses:
      if vocab[i] in c:
        if i not in dic:
          dic[i]=1
        elif i in dic:
          dic[i]+=1
      else:
        continue 

       # courseがvocab[i]を含めばdic[i]の値を1つ増やす
       # （dicにiのキーが存在しない場合に注意）
  
  return dic

`count_df`関数が完成したら、以下のセルを実行して動作を確認してください。辞書の長さは`243`、単語"プログラミング"（IDは`145`）のDFは`2`、単語"英語"（IDは`0`）のDFは`12`となります。

In [12]:
df = count_df(courses, vocab)
print(len(df))
print(vocab.index('プログラミング'), df[vocab.index('プログラミング')])
print(vocab.index('英語'), df[vocab.index('英語')])

243
145 2
0 12


## Q3
### Q3.1
リスト`vocab`の各単語を次元とする授業ベクトルを考えます。授業ベクトルの長さはリスト`vocab`の長さと等しく、リスト`vocab`のインデックス`i`の単語`vocab[i]`が授業名に含まれる時、授業ベクトルの`i`番目の要素は`1`、含まれなければ`0`とします。

以下では、リスト`courses`と`vocab`を引数で受け取り、リスト`courses`の各授業のベクトルを行、リスト`vocab`の各単語を列とした`NumPy`の行列を作成して返す`lec_word_matrix`関数を完成させてください。作成した授業-単語行列は、授業（行）の授業名に単語（列）が含まれていれば、その要素が1であるような行列です。

In [13]:
def lec_word_matrix(courses, vocab):
  ### 引数：
  # courses: 授業リスト
  # vocab: 単語リスト
  mat = np.zeros((len(courses),len(vocab)),dtype='int') # 授業数x単語数の0要素の行列を初期化
  for i in range(len(courses)):
    for j in range(len(vocab)):
      if vocab[j] in courses[i]:
        mat[i][j]=1
      else:
        continue



   # courses[i]がvocab[j]を含めばmat[i, j]の値を1
  return mat

`lec_word_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の形状は`(552, 243)`、要素の値の和は`2287`となります。

In [14]:
print(lec_word_matrix(courses, vocab).shape)
print(np.sum(lec_word_matrix(courses, vocab)))

(552, 243)
2287


### Q3.2
Q3.1で作成した授業-単語行列の各要素を、その授業の授業名に単語が含まれるか否かの1or0ではなく、その授業の授業名に単語が何回含まれるか（TF: Term Frequency)で表した行列を作成して返す`lec_word_tf_matrix`関数を完成させてください。

In [15]:
def lec_word_tf_matrix(courses, vocab):
  ### 引数：
  # courses: 授業リスト
  # vocab: 単語リスト
  mat = np.zeros((len(courses),len(vocab)),dtype='int') # 授業数x単語数の0要素の行列を初期化
  for i in range(len(courses)):
    for j in range(len(vocab)):
      num=courses[i].count(vocab[j])
      mat[i][j]=num 
   # courses[i]に含まれるvocab[j]の数をmat[i, j]の値に
  return mat

`lec_word_tf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の要素の値の和は`2366`となります。

授業「自然科学ゼミナール（情報科学）」には「科学」が2回含まれるので対応する行列の要素の値は2となります。

In [16]:
print(np.sum(lec_word_tf_matrix(courses, vocab)))
print(lec_word_tf_matrix(courses, vocab)[courses.index('自然科学ゼミナール（情報科学）'), vocab.index('科学')])

2366
2


### Q3.3
Q3.2で作成した授業-単語行列の各要素（授業`i`の単語`j`の$TF_{ij}$）にその単語のIDF値を掛けたTFIDF値を要素とする行列を作成して返す`lec_word_tfidf_matrix`関数を完成させてください。

ここで、授業`i`、単語`j`のTFIDF値は以下のように定義されます。
```Python
TFIDF=TF_ij*log(すべての授業数/単語jのDF)=TF_ij*log(len(courses)/df[j])
```
`log`の計算には`np.log()`が使用できます。

In [27]:
def lec_word_tfidf_matrix(courses, vocab, df):
  mat = np.zeros((len(courses),len(vocab))) # 授業数x単語数の0要素の行列を初期化
  for i in range(len(courses)):
    for j in range(len(vocab)):
      num=courses[i].count(vocab[j])
      mat[i][j]=num*np.log(len(courses)/df[j])
  return mat

`lec_word_tfidf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の要素の値の和の整数部分は`7274`となります。

講義「自然科学ゼミナール（情報科学）」には「科学」が2回含まれ、「科学」のDF値は75なので対応する行列の要素の値は$2*log(552/75)\simeq3.99$となります。

In [28]:
tfidf_mat = lec_word_tfidf_matrix(courses, vocab, df)
print(int(np.sum(tfidf_mat)))
print(df[vocab.index('科学')], tfidf_mat[courses.index('自然科学ゼミナール（情報科学）'), vocab.index('科学')])

7274
75 3.9921198654815697


## Q4
Q3.3で作成した授業-単語行列を元に、入力の授業に対してcos類似度に基づいて他のすべての授業との類似度を計算し、類似する授業名をキー、その類似度を値とした辞書を返す以下の`find_similar_course`関数を完成させてください。その際、**入力の授業および類似度が0の授業は辞書に含めない**ようにしてください。cos類似度の計算にはQ1で作成した関数を使ってもよいです。

In [68]:
def find_similar_course(target, tfidf_mat, courses):
  ### 引数：
  # target:  入力授業のID
  # tfidf_mat: Q3.3で作成した授業-単語行列
  # courses: 授業リスト
  dic={}
  a=tfidf_mat[target]
  for m in range(len(courses)):
    if m==target:
      continue
    s=tfidf_mat[m]
    res=cos_sim(a, s)
    if res>0 and res<1 :  
      dic[courses[m]]=res 
    else:
      continue
  # 入力授業のベクトルtfidf_mat[target]と各授業iのベクトルtfidf_mat[i]の類似度を計算
  return dic # 類似する授業名をキー、その類似度を値とする辞書を返す

`find_similar_course`関数が完成したら、以下のセルを実行して動作を確認してください。

入力の講義`自然科学ゼミナール（情報科学）`に類似した上位の講義は、`自然科学ゼミナール（生命科学）、生物情報科学、自然科学ゼミナール（数理科学）、自然現象とモデル、人類科学、...`となります。

類似した授業数は230となります。

In [69]:
tfidf_mat = lec_word_tfidf_matrix(courses, vocab, df)
title="自然科学ゼミナール（情報科学）" # 入力の授業名
results=find_similar_course(courses.index(title), tfidf_mat, courses) # 類似授業の辞書を受け取る
print(len(results)) # 類似授業の数
ranking = pd.DataFrame(list(results.items()), columns=['title', "similarity"]) # 類似度が上位の授業を表示
ranking.sort_values(by='similarity', ascending=False).head(10)

230


title  similarity
70                             自然科学ゼミナール（生命科学）    0.644874
88                                      生物情報科学    0.631863
68                             自然科学ゼミナール（数理科学）    0.622156
196                                   自然現象とモデル    0.399247
67                                        人類科学    0.387201
87                                        食の科学    0.387201
65                                      天然物の科学    0.387201
5                                           情報    0.332018
169   全学体験ゼミナール　(都市の緑のインタープリター養成－子どもに伝える自然体験－)    0.308337
120  全学自由研究ゼミナール　(ミュオグラフィ科学/Muography Science)    0.281423

## コードのテスト
以下のセルを実行してから、設問ごとにCheck関数でコードのテストをしてください。

In [31]:
# コードのテストの前にこのセルを実行してください
!pip install prog_edu_assistant_tools
import re
import sys
import jinja2
from IPython.core import display
from google.colab import _message as google_message
from prog_edu_assistant_tools.magics import report, autotest, CaptureOutput
from prog_edu_assistant_tools.check import Check

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 5.0 MB/s 


## Q1

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q1')

## Q2.1

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q2_1')

## Q2.2

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q2_2')

## Q3.1

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q3_1')

## Q3.2

In [ ]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q3_2')

## Q3.3

In [32]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q3_3')

## Q4

In [70]:
# Run this cell to check your solution.
# If you get an error 'Check not defined', make sure you have run all preceding
# cells once (Runtime -> Run before)
Check('q4')